apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: basic-example-templates
  description: A collection of example templates
spec:
  targets:
    - ./eks-cluster-template/template.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: basic-organization
  description: Basic organization data
spec:
  targets:
    - ./organization/guests.yaml